sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image

before_script:
- sudo apt-get install -qq -y xsltproc

script:
- bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "a32f33bb26d2"
  - COMMIT_AUTHOR_EMAIL: "thomas.buning@rwth-aachen.de"
