sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image

script:
- ./gradlew clean build
- mkdir $TRAVIS_BUILD_DIR/results
- docker run -v $TRAVIS_BUILD_DIR:/project thomasbuning/msa_intellij_docker_image /bin/sh -c "/opt/intellij/bin/inspect.sh /project /project/Default.xml /project/results -v2 -d /project/src"
- ls $TRAVIS_BUILD_DIR
- ls $TRAVIS_BUILD_DIR/results
- xsltproc /project/GraphQuery.xsl /project/results/GraphQuery.xml > /project/results/GraphQuery.xhtml
- cat /home/developer/.IdeaIC2017.1/system/log/idea.log
