sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image
- docker ps -a

script:
- docker run thomasbuning/msa_intellij_docker_image -v $TRAVIS_BUILD_DIR:/ /bin/sh -c "/opt/intellij/bin/inspect.sh /
Default.xml results-dir -v2"
