sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image

script:
- $TRAVIS_BUILD_DIR/gradlew clean build
- $TRAVIS_BUILD_DIR/gradlew dependencies
- mkdir $TRAVIS_BUILD_DIR/results
- docker run -v $TRAVIS_BUILD_DIR:/project thomasbuning/msa_intellij_docker_image /bin/sh -c "/opt/intellij/bin/inspect.sh /project /project/Default.xml /project/results -v2 -d /project/src && cp /home/developer/.IdeaIC2017.1/system/log/idea.log /project/results/idea.log"
- ls $TRAVIS_BUILD_DIR
- ls $TRAVIS_BUILD_DIR/results
- cat $TRAVIS_BUILD_DIR/results/idea.log
