sudo: required

language: ruby

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image

script:
- docker ps -a
- docker run -v $TRAVIS_BUILD_DIR:/project thomasbuning/msa_intellij_docker_image /bin/sh -c "/opt/intellij/bin/inspect.sh /project /project/Default.xml /project -v2"
