sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image

before_script:
- sudo apt-get install -qq -y xsltproc

script:
- mkdir $TRAVIS_BUILD_DIR/results
- docker run -v $TRAVIS_BUILD_DIR:/project thomasbuning/msa_intellij_docker_image /bin/sh -c "/opt/intellij/bin/inspect.sh /project /project/Default.xml /project/results -v2 -d /project/src"
- xsltproc $TRAVIS_BUILD_DIR/GraphQuery.xsl $TRAVIS_BUILD_DIR/results/GraphQuery.xml > $TRAVIS_BUILD_DIR/results/GraphQuery.xhtml
- find $TRAVIS_BUILD_DIR/results ! -name 'GraphQuery.xhtml' -type f -exec rm -f {} +

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 5SOM/+bZYinvK+1QRmm9B9A859Guw6/TiVYHytZj3u00y4uyDw/HBrxgJm/03O3fd/4VG6JpVmyUUI5m+RFldEvJFOwnkVx2qeTaP7M/qqQIuuXqRFJndhAkMG0TNsJbdgE7DM5EtgZvxce2Xe/zpdsoNl6iVn6QmE3/Y5WEpcc2blrrzieDyqKcqDU29Fx5NfSHgVaNsLzr3dlNXNOzj9z8NPo7OVyyl9sZbKHMnoGzpoP0Rops1Xtzrz5L2jF1bGS26Cx4mqnv9L+/cPLZeAYMa3cozaPsjL3UQ0w29q0OssP/jVnK76YRlbwvCoWood61YJE0fws2W1WhaAHy222492pgMjpHFPPbJEkmj0XytoxKSY0aHJCGyXIOlezuSnKfCugouS6adTAljdcrXNxCJECO/ojU0oacoSJtAyJFWjCSmK33h2qk9pnv66Z7NBKWP0rXSnKWljrx/mRN+CLhW1daZDBPgNCZkXDE14QS/wwQiD2y36GIUg4Ov1Cy9Rw5Rrn0GnnbuQ3Oix/zvU8HGvNeHqnlj7hwNSPkB/QvpH3NJC0YKwLKayKwwtyu3kXBsQfGZbqfDfZsQlXn273TQuS+hubZff+hmmRBbp+CHy6XPKpu+0Uq6F5yWDdB15i9wQcVyc4KPFykaRoGAloOqmSGfK3W+TxxRwA+Zgo=
  local_dir: $TRAVIS_BUILD_DIR/results
  target_branch: gh-pages
  email: thomas.buning@rwth-aachen.de
  overwrite: true
