sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image

before_script:
- sudo apt-get install -qq -y xsltproc

script:
- mkdir $TRAVIS_BUILD_DIR/results
- docker run -v $TRAVIS_BUILD_DIR:/project thomasbuning/msa_intellij_docker_image /bin/sh -c "/opt/intellij/bin/inspect.sh /project /project/Default.xml /project/results -v2 -d /project/src"
- xsltproc $TRAVIS_BUILD_DIR/GraphQuery.xsl $TRAVIS_BUILD_DIR/results/GraphQuery.xml > $TRAVIS_BUILD_DIR/results/GraphQuery.xhtml
- find $TRAVIS_BUILD_DIR/results ! -name 'GraphQuery.xhtml' -type f -exec rm -f {} +

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: $TRAVIS_BUILD_DIR/results
  target_branch: gh-pages
  email: thomas.buning@rwth-aachen.de
  overwrite: true
