sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
- docker pull thomasbuning/msa_intellij_docker_image

before_script:
- sudo apt-get install -qq -y xsltproc

script:
- mkdir $TRAVIS_BUILD_DIR/results
- docker run -v $TRAVIS_BUILD_DIR:/project thomasbuning/msa_intellij_docker_image /bin/sh -c "/opt/intellij/bin/inspect.sh /project /project/Default.xml /project/results -v2 -d /project/src && cp /home/developer/.IdeaIC2017.1/system/log/idea.log /project/results/idea.log"
- xsltproc $TRAVIS_BUILD_DIR/GraphQuery.xsl $TRAVIS_BUILD_DIR/results/GraphQuery.xml > $TRAVIS_BUILD_DIR/results/GraphQuery.xhtml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ALVfWl3tMDJfElFYS2OmM9RYGTvOIvMwPjLQ1Rx/iUCNdvihCLJqmM26zjvgcvDB8wS48IQP1lWqoAG4iIa93jru3er4tFb2J1MjAAWVoP7M9jjIRjFsCV0yX9VUXh7x0qoQa0cvgR1A49d/Ubg3nfhBgzLTgHHvNPkfAIXDTRZ2KIm/kDr5iVy3pcEx3XT+73mgqKS6wEKIcgvwVyXko94khc5WFxNc8+itx9yirMlrocXnWfMCMnnmYU6HaoWPDKEL8oeJWk84dyaeIHUd3q/AnWfZSnpU1JfyLVoJYEuX1vgGUFStGacDQAvVx4t+TOncg1SedJDJu4MKe3IXbLhLTpkOG1EEigiih+wyT+0SfclHnbj+bTwZex/Oix2ypNzqL0whGJTIwvo9zyBhjby5mqLluebBUst5+NtmUtohKNLlU6EQFDZ6E6LR/agQ+Axr9bDsJpIQY+nNRamfSYpf/ko//k5ONgBqBTSEj44Gl9HH2UI+WR8gKufo+dVtDlnrHYiqTvK4GH8jZ3R2ZAX4Ex2B2U8Yx292SFBFtm9/X0uRz4RXwkPGDKssdaoCv/Ve+r+Uo/AvitFVbmFXMpTXUe0nBdKSbaiQoefCZkseNLMVIQ7LmgGIvmzBXSsvc/paVEJGhJ7KgtTVCcM2MULWGwJSD869zB9pU0hnaWU=
  local_dir: $TRAVIS_BUILD_DIR/results
  on:
    branch: master
